Repository the-mvi/stat_an-2022, pull requests merged in 2022-12, with the labels that each got.

#23 0373_Vlasyuk_MV_task1
  0373_Vlasyuk_MV/task1.ipynb
Labels: invalid, check needed

#71 0373_Vlasyuk_MV_task2
  0373_Vlasyuk_MV/task2.ipynb
Labels: invalid, check needed

#33 0373_Savinov_AO_task1
  0373_Savinov_AO/task1.ipynb
  0373_Savinov_AO/Данные для практических работ.csv
Labels: invalid, check needed

#64 0373_Logunko_MK_task2
  0373_Logunko_MK/task2.ipynb
Labels: check needed

#81 0373_Dubova_VO_task3
  0373_Dubova_VO/task3.ipynb
Labels: question, check needed

#47 0373_Evdokimova_AG_task2
  0373_Evdokimova_AG/task2.ipynb
Labels: invalid, check needed

#66 0373_Myasnikov_YN_task2
  0373_Myasnikov_YN/task2.ipynb
Labels: invalid, check needed

#27 0373_Kurilov_AG_task1
  0373_Kurilov_AG/task1.ipynb
Labels: invalid, check needed

#85 0373_Golubev_AN_task3
  0373_Golubev_AN/task3.ipynb
Labels: invalid, check needed

#100 0373_Morev_IO_task1
  0373_Morev_IO/task1.ipynb
Labels: check needed

#112 0373_Morev_IO_task3
  0373_Morev_IO/task3.ipynb
Labels: invalid, check needed

#89 0373_Kurilov_AG_task2
  0373_Kurilov_AG/task2.ipynb
Labels: invalid, check needed

#120 0373_Shiryaev_NA_task3
  0373_Shiryaev_NA/task3.ipynb
Labels: invalid, check needed

#83 0373_Savinov_AO_task2
  0373_Savinov_AO/task2.ipynb
Labels: invalid, check needed

#116 0373_Kartashov_NA_task3
  0373_Kartashov_NA/task3.ipynb
Labels: check needed

#129 0373_Morev_IO_task2
  0373_Morev_IO/task2.ipynb
Labels: check needed
